//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.SomeStations
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class SomeStations { }
#else

	public class SomeStations : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public SomeStations()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/Vasttrafik;component/SampleData/SomeStations/SomeStations.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private ItemCollection _Collection = new ItemCollection();

		public ItemCollection Collection
		{
			get
			{
				return this._Collection;
			}
		}
	}

	public class ItemCollection : System.Collections.ObjectModel.ObservableCollection<Item>
	{ 
	}

	public class Item : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _Displayname = string.Empty;

		public string Displayname
		{
			get
			{
				return this._Displayname;
			}

			set
			{
				if (this._Displayname != value)
				{
					this._Displayname = value;
					this.OnPropertyChanged("Displayname");
				}
			}
		}

		private bool _IsFavorite = false;

		public bool IsFavorite
		{
			get
			{
				return this._IsFavorite;
			}

			set
			{
				if (this._IsFavorite != value)
				{
					this._IsFavorite = value;
					this.OnPropertyChanged("IsFavorite");
				}
			}
		}

		private string _FavoriteImage = string.Empty;

		public string FavoriteImage
		{
			get
			{
				return this._FavoriteImage;
			}

			set
			{
				if (this._FavoriteImage != value)
				{
					this._FavoriteImage = value;
					this.OnPropertyChanged("FavoriteImage");
				}
			}
		}

		private string _GoToState = string.Empty;

		public string GoToState
		{
			get
			{
				return this._GoToState;
			}

			set
			{
				if (this._GoToState != value)
				{
					this._GoToState = value;
					this.OnPropertyChanged("GoToState");
				}
			}
		}

		private string _CurrentState = string.Empty;

		public string CurrentState
		{
			get
			{
				return this._CurrentState;
			}

			set
			{
				if (this._CurrentState != value)
				{
					this._CurrentState = value;
					this.OnPropertyChanged("CurrentState");
				}
			}
		}
	}
#endif
}
